# Generated by Django 5.0 on 2023-12-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('compatibility_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtb_app.task')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qtb_app.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qtb_app.team'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtb_app.team'),
        ),
        migrations.AlterField(
            model_name='report',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtb_app.team'),
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
