# Generated by Django 5.0 on 2023-12-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtb_app', '0002_remove_employee_team_rename_reports_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='compatibility_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='performance_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
