# Generated by Django 5.0 on 2023-12-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtb_app', '0003_alter_team_compatibility_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qtb_app.task'),
        ),
    ]
