# Generated by Django 4.2.8 on 2023-12-30 06:21

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('qtb_app', '0004_alter_team_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_num',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
